apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: web
    name: web
    namespace: openfaas-fn
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            nodeSelector:
                kubernetes.io/hostname: "node1"
            containers:
            -   name: front-end
                image: sheldonchiu/web:final8
                ports:
                -   containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
    name: web-service
    namespace: openfaas-fn
spec:
    selector:
        app: web
    ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

---
apiVersion:  networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: traefik-ingress-web
    namespace: openfaas-fn
spec:
    rules:
    - host: test.comp4651.io
      http:
        paths:
          - path: /
            backend:
              serviceName:  web-service
              servicePort: 80