apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: web
    name: web
    namespace: openfaas-fn
spec:
    replicas: 2
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
            -   name: front-end
                image: sheldonchiu/comp4651-web:latest
                ports:
                - containerPort: 4000
            affinity:
                nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 50
                      preference:
                        matchExpressions:
                        - key: cloud.google.com/gke-nodepool
                          operator: In
                          values:
                          - default-pool
                        # topologyKey: kubernetes.io/hostname

# ---
# apiVersion: v1
# kind: Service
# metadata:
#     name: web-service
#     namespace: openfaas-fn
# spec:
#     type: LoadBalancer
#     selector:
#         app: web
#     ports:
#     - name: http
#       port: 80
#       targetPort: 4000

# ---
# apiVersion:  networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#     name: traefik-ingress-web
#     namespace: openfaas-fn
# spec:
#     rules:
#     - host: test.comp4651.io
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName:  web-service
#               servicePort: 80